### PR TITLE
Do not disconnect from VPN over cellular if security level is medium

### PR DESCRIPTION
**Pull request by ruimarinho**
I believe this was done in mistake as I don't see a reason for disconnecting over cellular when the security level is medium or higher. At least I would say it's safer if we simply ignore the directive.

### CODE REVIEW

**Comment by ruimarinho** [comment]
@iphoting have you given a thought to this yet?

**Comment by iphoting** [comment]
I don't disagree with your rationale. Just thinking over whether this is considered a "breaking change".
I'm inclined to think that this just requires a minor version bump with some behaviour change text within the change log.

What do you think?

**Comment by ruimarinho** [comment]
According to the README, under the `medium` level description it says _Else if the primary network interface becomes Cellular, leave any existing VPN connection up, but do not reconnect on demand._ I assume this is what `Ignore` would do, not `Disconnect`, right?

**Comment by iphoting** [comment]
Ok good point, it’ll be a bug fix. 
Will need to rebase this branch before merging.

**Comment by ruimarinho** [comment]
Done!

**Comment by iphoting** [comment]
Thanks for catching this!

**Pull request merged**
